"""impostos, despesas operacionais, fechamento mensal e custo de embalagem

Revision ID: 3956bfcd5c65
Revises: 5b72ed966a94
Create Date: 2026-08-10 12:44:41.597044

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3956bfcd5c65'
down_revision: str | None = '5b72ed966a94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_closes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cogs_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expenses_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('operating_profit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_closes')),
    sa.UniqueConstraint('tenant_id', 'month', name='uq_fechamento_tenant_mes')
    )
    op.create_index(op.f('ix_monthly_closes_tenant_id'), 'monthly_closes', ['tenant_id'], unique=False)
    op.create_table('operating_expenses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('competence_month', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_operating_expenses_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operating_expenses'))
    )
    op.create_index('ix_despesa_tenant_competencia', 'operating_expenses', ['tenant_id', 'competence_month'], unique=False)
    op.create_index(op.f('ix_operating_expenses_tenant_id'), 'operating_expenses', ['tenant_id'], unique=False)
    op.create_table('tax_rules',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('rate_pct', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('base', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tax_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_rules'))
    )
    op.create_index('ix_imposto_tenant_vigencia', 'tax_rules', ['tenant_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index(op.f('ix_tax_rules_tenant_id'), 'tax_rules', ['tenant_id'], unique=False)
    op.add_column('orders', sa.Column('sales_tax_amount', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('orders', sa.Column('tax_rule_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
    op.add_column('products', sa.Column('packaging_cost', sa.Numeric(precision=18, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'packaging_cost')
    op.drop_column('orders', 'tax_rule_id')
    op.drop_column('orders', 'sales_tax_amount')
    op.drop_index(op.f('ix_tax_rules_tenant_id'), table_name='tax_rules')
    op.drop_index('ix_imposto_tenant_vigencia', table_name='tax_rules')
    op.drop_table('tax_rules')
    op.drop_index(op.f('ix_operating_expenses_tenant_id'), table_name='operating_expenses')
    op.drop_index('ix_despesa_tenant_competencia', table_name='operating_expenses')
    op.drop_table('operating_expenses')
    op.drop_index(op.f('ix_monthly_closes_tenant_id'), table_name='monthly_closes')
    op.drop_table('monthly_closes')
    # ### end Alembic commands ###
