"""schema inicial completo

Revision ID: 5b72ed966a94
Revises: 
Create Date: 2026-08-10 00:47:25.259334

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5b72ed966a94'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.String(length=255), nullable=False),
    sa.Column('notify_webhook', sa.String(length=500), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index(op.f('ix_alert_rules_tenant_id'), 'alert_rules', ['tenant_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rule_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerta_tenant_data', 'alerts', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_entidade', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_data', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('manual_media_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('channel_account_id', 'external_id', name='uq_camp_conta_externo')
    )
    op.create_index('ix_camp_tenant_periodo', 'campaigns', ['tenant_id', 'start_at', 'end_at'], unique=False)
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_logs'))
    )
    op.create_index('ix_intlog_canal_data', 'integration_logs', ['channel', 'created_at'], unique=False)
    op.create_table('metrics_daily',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fees_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cogs_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cancelled_count', sa.Integer(), nullable=False),
    sa.Column('cancelled_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_ticket', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics_daily')),
    sa.UniqueConstraint('tenant_id', 'channel_account_id', 'day', name='uq_metrica_dia_conta_dia')
    )
    op.create_index('ix_metrica_dia_tenant', 'metrics_daily', ['tenant_id', 'day'], unique=False)
    op.create_index(op.f('ix_metrics_daily_tenant_id'), 'metrics_daily', ['tenant_id'], unique=False)
    op.create_table('metrics_hourly',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fees_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cancelled_count', sa.Integer(), nullable=False),
    sa.Column('cancelled_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics_hourly')),
    sa.UniqueConstraint('tenant_id', 'channel_account_id', 'channel', 'bucket', name='uq_metrica_hora_conta_canal_bucket')
    )
    op.create_index('ix_metrica_hora_tenant', 'metrics_hourly', ['tenant_id', 'bucket'], unique=False)
    op.create_index(op.f('ix_metrics_hourly_tenant_id'), 'metrics_hourly', ['tenant_id'], unique=False)
    op.create_table('metrics_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('value_num', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_text', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics_snapshots')),
    sa.UniqueConstraint('channel_account_id', 'day', 'metric', name='uq_snapshot_conta_dia_metrica')
    )
    op.create_index(op.f('ix_metrics_snapshots_tenant_id'), 'metrics_snapshots', ['tenant_id'], unique=False)
    op.create_index('ix_snapshot_tenant_dia', 'metrics_snapshots', ['tenant_id', 'day'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('code_verifier_enc', sa.LargeBinary(), nullable=True),
    sa.Column('redirect_after', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states')),
    sa.UniqueConstraint('state', name=op.f('uq_oauth_states_state'))
    )
    op.create_index(op.f('ix_oauth_states_tenant_id'), 'oauth_states', ['tenant_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('bank_reference', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements')),
    sa.UniqueConstraint('channel_account_id', 'external_id', name='uq_repasse_conta_externo')
    )
    op.create_index('ix_repasse_tenant_data', 'settlements', ['tenant_id', 'settlement_date'], unique=False)
    op.create_index(op.f('ix_settlements_tenant_id'), 'settlements', ['tenant_id'], unique=False)
    op.create_table('sku_pendencies',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sku_channel', sa.String(length=80), nullable=False),
    sa.Column('sample_title', sa.String(length=300), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku_pendencies')),
    sa.UniqueConstraint('tenant_id', 'channel', 'sku_channel', name='uq_pendencia_tenant_canal_sku')
    )
    op.create_index(op.f('ix_sku_pendencies_tenant_id'), 'sku_pendencies', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('external_event_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_webhook_events_idempotency_key'))
    )
    op.create_index('ix_webhook_canal_data', 'webhook_events', ['channel', 'received_at'], unique=False)
    op.create_index('ix_webhook_conta', 'webhook_events', ['channel_account_id', 'received_at'], unique=False)
    op.create_index('ix_webhook_fila', 'webhook_events', ['status', 'next_attempt_at'], unique=False)
    op.create_table('channel_accounts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_account_id', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=False),
    sa.Column('site_id', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_channel_accounts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_accounts')),
    sa.UniqueConstraint('tenant_id', 'channel', 'external_account_id', name='uq_conta_canal_externo')
    )
    op.create_index(op.f('ix_channel_accounts_tenant_id'), 'channel_accounts', ['tenant_id'], unique=False)
    op.create_index('ix_contas_tenant_canal', 'channel_accounts', ['tenant_id', 'channel'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=160), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ncm', sa.String(length=20), nullable=False),
    sa.Column('ean', sa.String(length=20), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_products_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_produto_tenant_sku')
    )
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('channel_credentials',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('access_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key_version', sa.SmallInteger(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], name=op.f('fk_channel_credentials_channel_account_id_channel_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_credentials'))
    )
    op.create_index('ix_cred_conta_atual', 'channel_credentials', ['channel_account_id', 'is_current'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('listing_type', sa.String(length=40), nullable=False),
    sa.Column('category_id', sa.String(length=40), nullable=False),
    sa.Column('sku_channel', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('sold_quantity', sa.Integer(), nullable=False),
    sa.Column('permalink', sa.String(length=500), nullable=False),
    sa.Column('thumbnail', sa.String(length=500), nullable=False),
    sa.Column('logistic_type', sa.String(length=40), nullable=False),
    sa.Column('health', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('visits_30d', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], name=op.f('fk_listings_channel_account_id_channel_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_listings_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings')),
    sa.UniqueConstraint('channel_account_id', 'external_id', name='uq_anuncio_conta_externo')
    )
    op.create_index('ix_anuncio_tenant_status', 'listings', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_listings_tenant_id'), 'listings', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('external_pack_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_raw', sa.String(length=60), nullable=False),
    sa.Column('status_detail', sa.String(length=120), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipping_revenue', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_source', sa.String(length=20), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('buyer_hash', sa.String(length=64), nullable=True),
    sa.Column('buyer_nickname', sa.String(length=120), nullable=False),
    sa.Column('ship_state', sa.String(length=40), nullable=False),
    sa.Column('ship_city', sa.String(length=120), nullable=False),
    sa.Column('logistic_type', sa.String(length=40), nullable=False),
    sa.Column('has_multiple_items', sa.Boolean(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], name=op.f('fk_orders_channel_account_id_channel_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_orders_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('channel_account_id', 'external_id', name='uq_pedido_conta_externo')
    )
    op.create_index(op.f('ix_orders_buyer_hash'), 'orders', ['buyer_hash'], unique=False)
    op.create_index('ix_orders_conta_data', 'orders', ['channel_account_id', 'date_created'], unique=False)
    op.create_index('ix_orders_geo', 'orders', ['tenant_id', 'ship_state', 'date_created'], unique=False)
    op.create_index('ix_orders_pack', 'orders', ['external_pack_id'], unique=False)
    op.create_index('ix_orders_tenant_data', 'orders', ['tenant_id', 'date_created'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index('ix_orders_tenant_status', 'orders', ['tenant_id', 'status', 'date_created'], unique=False)
    op.create_table('sku_links',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sku_channel', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sku_links_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku_links')),
    sa.UniqueConstraint('tenant_id', 'channel', 'sku_channel', name='uq_depara_tenant_canal_sku')
    )
    op.create_index(op.f('ix_sku_links_tenant_id'), 'sku_links', ['tenant_id'], unique=False)
    op.create_table('sync_cursors',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('resource', sa.String(length=40), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_external_id', sa.String(length=64), nullable=False),
    sa.Column('cursor_token', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=False),
    sa.Column('backfill_done', sa.Boolean(), nullable=False),
    sa.Column('progress_pct', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], name=op.f('fk_sync_cursors_channel_account_id_channel_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_cursors')),
    sa.UniqueConstraint('channel_account_id', 'resource', name='uq_cursor_conta_recurso')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('campaign_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('campaign_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('listing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('external_listing_id', sa.String(length=64), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('promo_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('stock_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_items_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_campaign_items_listing_id_listings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_items'))
    )
    op.create_index('ix_camp_item', 'campaign_items', ['campaign_id'], unique=False)
    op.create_index('ix_camp_item_anuncio', 'campaign_items', ['listing_id'], unique=False)
    op.create_index(op.f('ix_campaign_items_tenant_id'), 'campaign_items', ['tenant_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason_code', sa.String(length=60), nullable=False),
    sa.Column('reason_text', sa.String(length=400), nullable=False),
    sa.Column('resolution', sa.String(length=200), nullable=False),
    sa.Column('amount_involved', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_claims_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('channel_account_id', 'external_id', name='uq_recl_conta_externo')
    )
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    op.create_index('ix_recl_tenant_status', 'claims', ['tenant_id', 'status', 'opened_at'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('listing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('variation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_inventory_snapshots_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_snapshots'))
    )
    op.create_index('ix_estoque_anuncio_data', 'inventory_snapshots', ['listing_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_tenant_id'), 'inventory_snapshots', ['tenant_id'], unique=False)
    op.create_table('listing_variations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('listing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('external_variation_id', sa.String(length=64), nullable=False),
    sa.Column('sku_channel', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_listing_variations_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_variations')),
    sa.UniqueConstraint('listing_id', 'external_variation_id', name='uq_variacao_anuncio')
    )
    op.create_index(op.f('ix_listing_variations_tenant_id'), 'listing_variations', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('pack_id', sa.String(length=64), nullable=False),
    sa.Column('from_role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_messages_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('channel_account_id', 'external_id', name='uq_msg_conta_externo')
    )
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index('ix_msg_tenant_data', 'messages', ['tenant_id', 'sent_at'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    op.create_index('ix_evento_pedido_data', 'order_events', ['order_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_order_events_tenant_id'), 'order_events', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_raw', sa.String(length=60), nullable=False),
    sa.Column('status_detail', sa.String(length=80), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_paid_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('taxes_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_received_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('date_approved', sa.DateTime(timezone=True), nullable=True),
    sa.Column('money_release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('money_release_status', sa.String(length=30), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('channel_account_id', 'external_id', name='uq_pgto_conta_externo')
    )
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index('ix_pgto_liberacao', 'payments', ['tenant_id', 'money_release_date'], unique=False)
    op.create_index('ix_pgto_pedido', 'payments', ['order_id'], unique=False)
    op.create_index('ix_pgto_tenant_data', 'payments', ['tenant_id', 'date_approved'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('listing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('external_listing_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('asker_hash', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_answered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_questions_listing_id_listings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('channel_account_id', 'external_id', name='uq_pergunta_conta_externo')
    )
    op.create_index('ix_pergunta_tenant_status', 'questions', ['tenant_id', 'status', 'date_created'], unique=False)
    op.create_index(op.f('ix_questions_tenant_id'), 'questions', ['tenant_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('expected_net', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('settled_net', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('divergence', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('divergence_pct', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reconciliations_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliations')),
    sa.UniqueConstraint('order_id', name='uq_conciliacao_pedido')
    )
    op.create_index('ix_concil_tenant_status', 'reconciliations', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_reconciliations_tenant_id'), 'reconciliations', ['tenant_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('listing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_reviews_listing_id_listings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reviews_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('channel_account_id', 'external_id', name='uq_aval_conta_externo')
    )
    op.create_index('ix_aval_tenant_data', 'reviews', ['tenant_id', 'date_created'], unique=False)
    op.create_index(op.f('ix_reviews_tenant_id'), 'reviews', ['tenant_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_raw', sa.String(length=60), nullable=False),
    sa.Column('substatus', sa.String(length=60), nullable=False),
    sa.Column('tracking_number', sa.String(length=80), nullable=False),
    sa.Column('carrier', sa.String(length=80), nullable=False),
    sa.Column('logistic_type', sa.String(length=40), nullable=False),
    sa.Column('date_shipped', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_delivered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('cost_seller', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cost_buyer', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('receiver_state', sa.String(length=40), nullable=False),
    sa.Column('receiver_city', sa.String(length=120), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_shipments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments')),
    sa.UniqueConstraint('channel_account_id', 'external_id', name='uq_envio_conta_externo')
    )
    op.create_index('ix_envio_atraso', 'shipments', ['tenant_id', 'estimated_delivery'], unique=False)
    op.create_index('ix_envio_tenant_status', 'shipments', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_shipments_tenant_id'), 'shipments', ['tenant_id'], unique=False)
    op.create_table('claim_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('claim_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_events_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_events'))
    )
    op.create_index(op.f('ix_claim_events_tenant_id'), 'claim_events', ['tenant_id'], unique=False)
    op.create_index('ix_evento_recl_data', 'claim_events', ['claim_id', 'occurred_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('external_item_id', sa.String(length=64), nullable=False),
    sa.Column('listing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('variation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sku_channel', sa.String(length=80), nullable=False),
    sa.Column('sku_base', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('variation_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_order_items_listing_id_listings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variation_id'], ['listing_variations.id'], name=op.f('fk_order_items_variation_id_listing_variations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_item_pedido', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_item_produto', 'order_items', ['product_id'], unique=False)
    op.create_index('ix_item_sku', 'order_items', ['tenant_id', 'sku_base'], unique=False)
    op.create_index(op.f('ix_order_items_tenant_id'), 'order_items', ['tenant_id'], unique=False)
    op.create_table('payment_fees',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('payment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('fee_type', sa.String(length=40), nullable=False),
    sa.Column('fee_type_raw', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payer', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_fees_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_fees'))
    )
    op.create_index(op.f('ix_payment_fees_tenant_id'), 'payment_fees', ['tenant_id'], unique=False)
    op.create_index('ix_taxa_pgto', 'payment_fees', ['payment_id'], unique=False)
    op.create_index('ix_taxa_tipo', 'payment_fees', ['tenant_id', 'fee_type'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('payment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_chargeback', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index('ix_reemb_tenant_data', 'refunds', ['tenant_id', 'date_created'], unique=False)
    op.create_index(op.f('ix_refunds_tenant_id'), 'refunds', ['tenant_id'], unique=False)
    op.create_table('settlement_entries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('settlement_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('payment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('entry_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_settlement_entries_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_settlement_entries_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name=op.f('fk_settlement_entries_settlement_id_settlements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_entries'))
    )
    op.create_index('ix_linha_pgto', 'settlement_entries', ['payment_id'], unique=False)
    op.create_index('ix_linha_repasse', 'settlement_entries', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_settlement_entries_tenant_id'), 'settlement_entries', ['tenant_id'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('shipment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('substatus', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_shipment_events_shipment_id_shipments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_events'))
    )
    op.create_index('ix_evento_envio_data', 'shipment_events', ['shipment_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_shipment_events_tenant_id'), 'shipment_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_events_tenant_id'), table_name='shipment_events')
    op.drop_index('ix_evento_envio_data', table_name='shipment_events')
    op.drop_table('shipment_events')
    op.drop_index(op.f('ix_settlement_entries_tenant_id'), table_name='settlement_entries')
    op.drop_index('ix_linha_repasse', table_name='settlement_entries')
    op.drop_index('ix_linha_pgto', table_name='settlement_entries')
    op.drop_table('settlement_entries')
    op.drop_index(op.f('ix_refunds_tenant_id'), table_name='refunds')
    op.drop_index('ix_reemb_tenant_data', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_taxa_tipo', table_name='payment_fees')
    op.drop_index('ix_taxa_pgto', table_name='payment_fees')
    op.drop_index(op.f('ix_payment_fees_tenant_id'), table_name='payment_fees')
    op.drop_table('payment_fees')
    op.drop_index(op.f('ix_order_items_tenant_id'), table_name='order_items')
    op.drop_index('ix_item_sku', table_name='order_items')
    op.drop_index('ix_item_produto', table_name='order_items')
    op.drop_index('ix_item_pedido', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_evento_recl_data', table_name='claim_events')
    op.drop_index(op.f('ix_claim_events_tenant_id'), table_name='claim_events')
    op.drop_table('claim_events')
    op.drop_index(op.f('ix_shipments_tenant_id'), table_name='shipments')
    op.drop_index('ix_envio_tenant_status', table_name='shipments')
    op.drop_index('ix_envio_atraso', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_reviews_tenant_id'), table_name='reviews')
    op.drop_index('ix_aval_tenant_data', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reconciliations_tenant_id'), table_name='reconciliations')
    op.drop_index('ix_concil_tenant_status', table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_questions_tenant_id'), table_name='questions')
    op.drop_index('ix_pergunta_tenant_status', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_pgto_tenant_data', table_name='payments')
    op.drop_index('ix_pgto_pedido', table_name='payments')
    op.drop_index('ix_pgto_liberacao', table_name='payments')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_events_tenant_id'), table_name='order_events')
    op.drop_index('ix_evento_pedido_data', table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('ix_msg_tenant_data', table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_listing_variations_tenant_id'), table_name='listing_variations')
    op.drop_table('listing_variations')
    op.drop_index(op.f('ix_inventory_snapshots_tenant_id'), table_name='inventory_snapshots')
    op.drop_index('ix_estoque_anuncio_data', table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index('ix_recl_tenant_status', table_name='claims')
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_campaign_items_tenant_id'), table_name='campaign_items')
    op.drop_index('ix_camp_item_anuncio', table_name='campaign_items')
    op.drop_index('ix_camp_item', table_name='campaign_items')
    op.drop_table('campaign_items')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('sync_cursors')
    op.drop_index(op.f('ix_sku_links_tenant_id'), table_name='sku_links')
    op.drop_table('sku_links')
    op.drop_index('ix_orders_tenant_status', table_name='orders')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index('ix_orders_tenant_data', table_name='orders')
    op.drop_index('ix_orders_pack', table_name='orders')
    op.drop_index('ix_orders_geo', table_name='orders')
    op.drop_index('ix_orders_conta_data', table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_hash'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_listings_tenant_id'), table_name='listings')
    op.drop_index('ix_anuncio_tenant_status', table_name='listings')
    op.drop_table('listings')
    op.drop_index('ix_cred_conta_atual', table_name='channel_credentials')
    op.drop_table('channel_credentials')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_contas_tenant_canal', table_name='channel_accounts')
    op.drop_index(op.f('ix_channel_accounts_tenant_id'), table_name='channel_accounts')
    op.drop_table('channel_accounts')
    op.drop_index('ix_webhook_fila', table_name='webhook_events')
    op.drop_index('ix_webhook_conta', table_name='webhook_events')
    op.drop_index('ix_webhook_canal_data', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_sku_pendencies_tenant_id'), table_name='sku_pendencies')
    op.drop_table('sku_pendencies')
    op.drop_index(op.f('ix_settlements_tenant_id'), table_name='settlements')
    op.drop_index('ix_repasse_tenant_data', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_oauth_states_tenant_id'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index('ix_snapshot_tenant_dia', table_name='metrics_snapshots')
    op.drop_index(op.f('ix_metrics_snapshots_tenant_id'), table_name='metrics_snapshots')
    op.drop_table('metrics_snapshots')
    op.drop_index(op.f('ix_metrics_hourly_tenant_id'), table_name='metrics_hourly')
    op.drop_index('ix_metrica_hora_tenant', table_name='metrics_hourly')
    op.drop_table('metrics_hourly')
    op.drop_index(op.f('ix_metrics_daily_tenant_id'), table_name='metrics_daily')
    op.drop_index('ix_metrica_dia_tenant', table_name='metrics_daily')
    op.drop_table('metrics_daily')
    op.drop_index('ix_intlog_canal_data', table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_index('ix_camp_tenant_periodo', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_audit_tenant_data', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_entidade', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index('ix_alerta_tenant_data', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_alert_rules_tenant_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
