"""custo de aquisicao e simples nacional progressivo

Revision ID: 734efb8728a7
Revises: 3956bfcd5c65
Create Date: 2026-08-10 16:48:16.859850

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '734efb8728a7'
down_revision: str | None = '3956bfcd5c65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_brackets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tax_rule_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rbt12_ate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('aliquota_nominal_pct', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('parcela_deduzir', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['tax_rule_id'], ['tax_rules.id'], name=op.f('fk_tax_brackets_tax_rule_id_tax_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_brackets')),
    sa.UniqueConstraint('tax_rule_id', 'rbt12_ate', name='uq_faixa_regra_teto')
    )
    op.create_index(op.f('ix_tax_brackets_tax_rule_id'), 'tax_brackets', ['tax_rule_id'], unique=False)
    op.create_index(op.f('ix_tax_brackets_tenant_id'), 'tax_brackets', ['tenant_id'], unique=False)
    # ``server_default`` é obrigatório aqui: sem ele, adicionar coluna NOT NULL
    # numa tabela que já tem linhas falha no Postgres. O default fica no banco
    # apenas para preencher o passado — o valor de novas linhas continua vindo
    # do modelo.
    op.add_column(
        'products',
        sa.Column('freight_in_cost', sa.Numeric(precision=18, scale=4),
                  nullable=False, server_default='0'),
    )
    op.add_column(
        'products',
        sa.Column('other_acquisition_cost', sa.Numeric(precision=18, scale=4),
                  nullable=False, server_default='0'),
    )
    op.add_column(
        'tax_rules',
        sa.Column('regime', sa.String(length=30), nullable=False,
                  server_default='fixed'),
    )
    op.add_column(
        'tax_rules',
        sa.Column('annex', sa.String(length=60), nullable=False, server_default=''),
    )

    # O default existia só para preencher as linhas já gravadas. Mantê-lo faria
    # o schema divergir do modelo e todo autogenerate futuro acusar drift.
    #
    # Só no Postgres: o SQLite não implementa ALTER COLUMN DROP DEFAULT, e
    # removê-lo exigiria reconstruir a tabela inteira — custo sem retorno num
    # banco que só existe em desenvolvimento e teste.
    if op.get_bind().dialect.name == 'postgresql':
        for tabela, coluna in (
            ('products', 'freight_in_cost'),
            ('products', 'other_acquisition_cost'),
            ('tax_rules', 'regime'),
            ('tax_rules', 'annex'),
        ):
            op.alter_column(tabela, coluna, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_rules', 'annex')
    op.drop_column('tax_rules', 'regime')
    op.drop_column('products', 'other_acquisition_cost')
    op.drop_column('products', 'freight_in_cost')
    op.drop_index(op.f('ix_tax_brackets_tenant_id'), table_name='tax_brackets')
    op.drop_index(op.f('ix_tax_brackets_tax_rule_id'), table_name='tax_brackets')
    op.drop_table('tax_brackets')
    # ### end Alembic commands ###
